### ISSUE TITLE
Add compatibility to PHPUnit 10 

### ISSUE THREAD

**Issue by acardielwata** [Kocal/SymfonyMailerTesting#33]
I'm trying to update my project to PHPUnit 10 (10.4), and I get this compatibility error:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires kocal/symfony-mailer-testing ^1.0 -> satisfiable by kocal/symfony-mailer-testing[1.0.0, 1.0.1].
    - kocal/symfony-mailer-testing[1.0.0, ..., 1.0.1] require phpunit/phpunit ^8.5 || ^9.0 -> found phpunit/phpunit[8.5.0, ..., 8.5.34, 9.0.0, ..., 9.6.13] but it conflicts with your root composer.json require (^10.4).`
    
    Has this project in their roadmap the idea to upgrade dependencies to make it compatible with new versions of PHPUnit?
    
    Thanks in advance!

**Comment by Kocal** [comment]
Hi,

Would you mind sending a PR?

**Comment by Kocal** [comment]
Done in #34
